package com.example.ryady

data class Variant(
    val id: Long,
    val productId: Long,
    val title: String,
    val price: String,
    val sku: String,
    val position: Long,
    val inventoryPolicy: String,
    val compareAtPrice: String?,
    val fulfillmentService: String,
    val inventoryManagement: String,
    val option1: String,
    val option2: String,
    val option3: Any?,
    val createdAt: String,
    val updatedAt: String,
    val taxable: Boolean,
    val barcode: Any?,
    val grams: Long,
    val weight: Double,
    val weightUnit: String,
    val inventoryItemId: Long,
    val inventoryQuantity: Long,
    val oldInventoryQuantity: Long,
    val requiresShipping: Boolean,
    val adminGraphqlApiId: String,
    val imageId: Any?,
)
